### ISSUE TITLE
can't meet the requirement of codes

### ISSUE THREAD

**Issue by CrystalSixone** [YuankaiQi/REVERIE#12]
Hi! I am trying to run your codes following readme.md, and I have installed CUDA-9.0 and pytorch-0.4.0, just as mentioned. However, I still can't run the codes successfully. When I run: `python tasks/REVERIE/trainFast.py --feedback_method sample2step --experiment_name releaseCheck` I meet this error:
`RuntimeError: cublas runtime error : the GPU program failed to execute at /opt/conda/conda-bld/pytorch_1524584710464/work/aten/src/THC/THCBlas.cu:249`
It seems that my GPU version (RTX-2060) just can't support CUDA-9.0. 
I don't know if there is any method to address this problem, and look forward to your update for the codes.
Thx :)

**Comment by YuankaiQi** [comment]
Hi, try the updates [here](https://github.com/YuankaiQi/REVERIE/blob/master/README.md#0)
