### ISSUE TITLE
Can you provide simple example about how to integrate with external project?

### ISSUE THREAD

**Issue by yahoo17** [YuankaiQi/REVERIE#13]
I would like to make a service, the input is the instruction, and the output is the trajectory

**Comment by YuankaiQi** [comment]
The integrating example will be released very soon for the REVERIE Challenge 2022, please stay tuned. If you mean the previous REVERIE, please refer to [here](https://github.com/YuankaiQi/REVERIE#6)

**Comment by YuankaiQi** [comment]
The grounding part after navigation has been released [here](https://github.com/zhaoc5/Grounding-REVERIE-Challenge/blob/main/eval.sh).
