### ISSUE TITLE
Does it  exists the data file "REVERIE_val_train_seen.json"?

### ISSUE THREAD

**Issue by JeremyLinky** [YuankaiQi/REVERIE#15]
Hi, I am recently running the recurrent VLN on REVERIE.  It prompts me that this data file "REVERIE_val_train_seen.json"  is missing.  But I couldn't find it in your project. Does this file exist? If it exists, could you provide it for me? Thanks!

**Comment by YuankaiQi** [comment]
REVERIE does not have such a split. I think you can make one from the training split.

**Comment by JeremyLinky** [comment]
Thanks for your advice!
