### ISSUE TITLE
Got the zero metrics of RGS and RGSPL

### ISSUE THREAD

**Issue by JeremyLinky** [YuankaiQi/REVERIE#16]

**Comment by JeremyLinky** [comment]
Hi, Yuankai,
     I submitted the results of test split and got the zero metrics of RGS and RGSPL, the other metrics seem normal. Could you help me know what is the reason?
An example of my result is as follows:
`  {
    "instr_id": "619_0",
    "trajectory": [
      [
        "33da8b14bc224e7e93045cf3e8ba88f1",
        0.0,
        0.0
      ],
      [
        "f53c36c7f710428e8968b95e8d7171c2",
        0.0,
        0.0
      ],
      [
        "9adb4cea1434445d81f50b9890c88cb2",
        0.0,
        0.0
      ],
      [
        "ffbe14a1bab6497abb439dfcc3cfd11e",
        0.0,
        0.0
      ],
      [
        "200d479334cf48f99d62da575fd48cc6",
        0.0,
        0.0
      ],
      [
        "9fa882fcc3e3446a9479a17e534a2f62",
        0.0,
        0.0
      ],
      [
        "13ae1603f381466a86b3d1dcc884366c",
        0.0,
        0.0
      ],
      [
        "536fbbcaf1054b97afd961dd2cf0ff30",
        0.0,
        0.0
      ]
    ],
    "predObjId": "283"
  },`

**Comment by YuankaiQi** [comment]
The predObjId should be an integer instead of a string.
