### ISSUE TITLE
Models implementation

### ISSUE THREAD

**Issue by rmant** [YuankaiQi/REVERIE#2]
Hello, are you planning to release the code to train baselines and your Navigator-Pointer model anytime soon?

Great contribution by the way, I loved your paper.

**Comment by YuankaiQi** [comment]
> Hello, are you planning to release the code to train baselines and your Navigator-Pointer model anytime soon?
> 
> Great contribution by the way, I loved your paper.

Thanks for your interests : ) We will release the code soon. It is for training and evaluating the Navigator-Pointer model. For test split evaluation, one needs to submit to our evaluating server, which will be ready very soon. BTW, a REVERIE challenge is also coming together.
