### ISSUE TITLE
Upgrading Pytorch version

### ISSUE THREAD

**Issue by guhur** [YuankaiQi/REVERIE#6]
Hi,

Thanks for sharing this code!

It would be nice to bump up the pytorch version. 0.4.0 is very old and a lot has changed since. Also it means we can't use allennlp and a lot of other great librairies.

This requires some efforts, since for now, MattNet does not compile pytorch 1.7.0. Moreover, a few breaking (but silent) changes were made at PyTorch 1.1: the code could work but not reproducing existing baselines.

Thanks

**Comment by YuankaiQi** [comment]
A new version for the Pointer is on the way

**Comment by YuankaiQi** [comment]
Hi, please refer to the updates [here](https://github.com/YuankaiQi/REVERIE/blob/master/README.md#0)
