### ISSUE TITLE
Empty bounding boxes

### ISSUE THREAD

**Issue by guhur** [YuankaiQi/REVERIE#8]
Hi Yuankai,

Thanks for your new dataset!

Some objects have no bounding boxes in their description. For example: https://github.com/YuankaiQi/REVERIE/blob/master/tasks/REVERIE/data/BBox/mJXqzFtmKg4_929158cc8c424c099a601a36e0fc2270.json

This seems to affect a large number of bounding boxes. Do you know why is it like this? Is there some way to recover the missing bounding boxes? 

Thanks for your answer.

**Comment by guhur** [comment]
Here is my count of such empty bounding boxes files per dataset split:

train 740
test 546
val_seen 1853
val_unseen 213

**Comment by guhur** [comment]
Only one sample from the training set is actually affected: 1513_273  on the training set, whose last viewpoint is https://github.com/YuankaiQi/REVERIE/blob/master/tasks/REVERIE/data/BBox/mJXqzFtmKg4_929158cc8c424c099a601a36e0fc2270.json

**Comment by YuankaiQi** [comment]
Hi guhur,

Thanks for your valuable feedback! 

Unfortunately, we currently are not sure about the reason for it. The good news is that we are developing a better simulator to render more precise bounding boxes.  Much denser bounding boxes will be first released after the 2nd REVERIE challenge, and we will fix these issues. Please stay tuned.

Best,

**Comment by guhur** [comment]
Good to know thanks :)
