### ISSUE TITLE
How to correctly interpret the object names?

### ISSUE THREAD

**Issue by Jackie-Chou** [YuankaiQi/REVERIE#9]
Hi, I am very interested in the REVERIE data, especially the BBOX annotations of different objects in Matterport3D. 
However, I've got confused by the object names. Most of the names are single-word nouns which are eay to understand, like toilet. But I noticed there were also some compound objects with names composed of multiple words connected by special symbols like # and /. For example, there are floor#/#room#above, dining#chair, etc. So I just want to ask how should I understand these compound names, e.g., what is the rule for using different symbols like # and /.

**Comment by YuankaiQi** [comment]
Thanks for your interest in our work! The object labels are adopted from the Matterport 3D dataset without modification. It seems to me that symbols like # and / are just used to separate words.
